project_id = "cguaakdjeejghgzruerc"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-export-user-data]
verify_jwt = false

[functions.claim-invite]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
